name: CMIConfigDialogs
version: '${version}'
main: cl.charlys.cmiconfig.CMIConfigDialogsPlugin
api-version: '1.21'
authors: [Italo]
description: Panel de configuracion por Dialogs para CMI.
depend: [CMI, CMILib]
commands:
  cmiconfig:
    description: Abre y administra el panel visual de CMI.
    usage: /cmiconfig
    permission: cmiconfig.admin
permissions:
  cmiconfig.admin:
    description: Permite administrar CMI desde CMIConfigDialogs.
    default: op
